#include "c_backend_internal.h"

/* Each generated line remains separate in this table so emitted C is easy to
 * inspect and the small runtime stays allocation-free. */
static const char *runtime_lines[] = {
    "#include <stdbool.h>",
    "#include <limits.h>",
    "#include <math.h>",
    "#include <stddef.h>",
    "#include <stdint.h>",
    "#include <stdio.h>",
    "#include <stdlib.h>",
    "#include <string.h>",
    "typedef int32_t USKInt;",
    "typedef int64_t USKLong;",
    "typedef int8_t USKShort;",
    "typedef double USKDouble;",
    "typedef float USKFloat;",
    "typedef const char *USKString;",
    "typedef char USKChar;",
    "typedef bool USKBool;",
    "typedef void *USKNull;",
    "typedef struct {",
    "    unsigned kind;",
    "    union { long long integer; double number; const char *text; bool boolean; } as;",
    "} UskFmtArg;",
    "enum { USK_FMT_INTEGER, USK_FMT_DOUBLE, USK_FMT_STRING, USK_FMT_BOOL, USK_FMT_NULL };",
    "static UskFmtArg usk_fmt_integer(long long value) {",
    "    UskFmtArg result = { .kind = USK_FMT_INTEGER, .as.integer = value };",
    "    return result;",
    "}",
    "static UskFmtArg usk_fmt_double(double value) {",
    "    UskFmtArg result = { .kind = USK_FMT_DOUBLE, .as.number = value };",
    "    return result;",
    "}",
    "static UskFmtArg usk_fmt_string(const char *value) {",
    "    UskFmtArg result = { .kind = USK_FMT_STRING, .as.text = value };",
    "    return result;",
    "}",
    "static UskFmtArg usk_fmt_boolean(bool value) {",
    "    UskFmtArg result = { .kind = USK_FMT_BOOL, .as.boolean = value };",
    "    return result;",
    "}",
    "static UskFmtArg usk_fmt_null(const void *value) {",
    "    (void)value;",
    "    UskFmtArg result = { .kind = USK_FMT_NULL };",
    "    return result;",
    "}",
    "#define USK_FMT_ARG(value) _Generic((value), const char *: usk_fmt_string, char *: usk_fmt_string, double: usk_fmt_double, float: usk_fmt_double, bool: usk_fmt_boolean, void *: usk_fmt_null, const void *: usk_fmt_null, default: usk_fmt_integer)(value)",
    "static inline void usk_numeric_fail(const char *reason) {",
    "    fprintf(stderr, \"usk native runtime: %s\\n\", reason);",
    "    exit(70);",
    "}",
    "static inline USKInt usk_i32_add(USKInt left, USKInt right) {",
    "    int64_t value = (int64_t)left + (int64_t)right;",
    "    if (value < INT32_MIN || value > INT32_MAX) usk_numeric_fail(\"USKInt addition overflow\");",
    "    return (USKInt)value;",
    "}",
    "static inline USKInt usk_i32_subtract(USKInt left, USKInt right) {",
    "    int64_t value = (int64_t)left - (int64_t)right;",
    "    if (value < INT32_MIN || value > INT32_MAX) usk_numeric_fail(\"USKInt subtraction overflow\");",
    "    return (USKInt)value;",
    "}",
    "static inline USKInt usk_i32_multiply(USKInt left, USKInt right) {",
    "    int64_t value = (int64_t)left * (int64_t)right;",
    "    if (value < INT32_MIN || value > INT32_MAX) usk_numeric_fail(\"USKInt multiplication overflow\");",
    "    return (USKInt)value;",
    "}",
    "static inline USKInt usk_i32_divide(USKInt left, USKInt right) {",
    "    if (!right) usk_numeric_fail(\"USKInt division by zero\");",
    "    if (left == INT32_MIN && right == -1) usk_numeric_fail(\"USKInt division overflow\");",
    "    return left / right;",
    "}",
    "static inline USKInt usk_i32_remainder(USKInt left, USKInt right) {",
    "    if (!right) usk_numeric_fail(\"USKInt remainder by zero\");",
    "    if (left == INT32_MIN && right == -1) return 0;",
    "    return left % right;",
    "}",
    "static inline USKInt usk_i32_negate(USKInt value) {",
    "    if (value == INT32_MIN) usk_numeric_fail(\"USKInt negation overflow\");",
    "    return -value;",
    "}",
    "static inline USKInt usk_i32_pre_increment(USKInt *value) { *value = usk_i32_add(*value, 1); return *value; }",
    "static inline USKInt usk_i32_post_increment(USKInt *value) { USKInt old = *value; *value = usk_i32_add(*value, 1); return old; }",
    "static inline USKInt usk_i32_pre_decrement(USKInt *value) { *value = usk_i32_subtract(*value, 1); return *value; }",
    "static inline USKInt usk_i32_post_decrement(USKInt *value) { USKInt old = *value; *value = usk_i32_subtract(*value, 1); return old; }",
    "static inline int64_t usk_i64_add(int64_t left, int64_t right) {",
    "    if ((right > 0 && left > INT64_MAX - right) || (right < 0 && left < INT64_MIN - right)) usk_numeric_fail(\"USKLong addition overflow\");",
    "    return left + right;",
    "}",
    "static inline int64_t usk_i64_subtract(int64_t left, int64_t right) {",
    "    if ((right < 0 && left > INT64_MAX + right) || (right > 0 && left < INT64_MIN + right)) usk_numeric_fail(\"USKLong subtraction overflow\");",
    "    return left - right;",
    "}",
    "static inline int64_t usk_i64_multiply(int64_t left, int64_t right) {",
    "    if (!left || !right) return 0;",
    "    if ((left == -1 && right == INT64_MIN) || (right == -1 && left == INT64_MIN)) usk_numeric_fail(\"USKLong multiplication overflow\");",
    "    if (left > 0 && ((right > 0 && left > INT64_MAX / right) || (right < 0 && right < INT64_MIN / left))) usk_numeric_fail(\"USKLong multiplication overflow\");",
    "    if (left < 0 && ((right > 0 && left < INT64_MIN / right) || (right < 0 && left < INT64_MAX / right))) usk_numeric_fail(\"USKLong multiplication overflow\");",
    "    return left * right;",
    "}",
    "static inline int64_t usk_i64_divide(int64_t left, int64_t right) {",
    "    if (!right) usk_numeric_fail(\"USKLong division by zero\");",
    "    if (left == INT64_MIN && right == -1) usk_numeric_fail(\"USKLong division overflow\");",
    "    return left / right;",
    "}",
    "static inline int64_t usk_i64_remainder(int64_t left, int64_t right) {",
    "    if (!right) usk_numeric_fail(\"USKLong remainder by zero\");",
    "    if (left == INT64_MIN && right == -1) return 0;",
    "    return left % right;",
    "}",
    "static inline int64_t usk_i64_negate(int64_t value) {",
    "    if (value == INT64_MIN) usk_numeric_fail(\"USKLong negation overflow\");",
    "    return -value;",
    "}",
    "static inline int64_t usk_i64_pre_increment(int64_t *value) { *value = usk_i64_add(*value, 1); return *value; }",
    "static inline int64_t usk_i64_post_increment(int64_t *value) { int64_t old = *value; *value = usk_i64_add(*value, 1); return old; }",
    "static inline int64_t usk_i64_pre_decrement(int64_t *value) { *value = usk_i64_subtract(*value, 1); return *value; }",
    "static inline int64_t usk_i64_post_decrement(int64_t *value) { int64_t old = *value; *value = usk_i64_subtract(*value, 1); return old; }",
    "static inline double usk_f64_check(double value) {",
    "    if (!isfinite(value)) usk_numeric_fail(\"USKDouble result is not finite\");",
    "    return value;",
    "}",
    "static inline double usk_f64_add(double left, double right) { return usk_f64_check(left + right); }",
    "static inline double usk_f64_subtract(double left, double right) { return usk_f64_check(left - right); }",
    "static inline double usk_f64_multiply(double left, double right) { return usk_f64_check(left * right); }",
    "static inline double usk_f64_divide(double left, double right) {",
    "    if (right == 0.0) usk_numeric_fail(\"USKDouble division by zero\");",
    "    return usk_f64_check(left / right);",
    "}",
    "static inline double usk_f64_pre_increment(double *value) { *value = usk_f64_check(*value + 1.0); return *value; }",
    "static inline double usk_f64_post_increment(double *value) { double old = *value; *value = usk_f64_check(*value + 1.0); return old; }",
    "static inline double usk_f64_pre_decrement(double *value) { *value = usk_f64_check(*value - 1.0); return *value; }",
    "static inline double usk_f64_post_decrement(double *value) { double old = *value; *value = usk_f64_check(*value - 1.0); return old; }",
    "static inline bool usk_string_truthy(const char *value) { return value && value[0] != '\\0'; }",
    "static inline int usk_string_compare(const char *left, const char *right) {",
    "    if (!left) left = \"\";",
    "    if (!right) right = \"\";",
    "    return strcmp(left, right);",
    "}",
    "static void usk_print_arg(UskFmtArg value) {",
    "    switch (value.kind) {",
    "        case USK_FMT_INTEGER: fprintf(stdout, \"%lld\", value.as.integer); break;",
    "        case USK_FMT_DOUBLE: fprintf(stdout, \"%.17g\", value.as.number); break;",
    "        case USK_FMT_STRING: fputs(value.as.text ? value.as.text : \"\", stdout); break;",
    "        case USK_FMT_BOOL: fputs(value.as.boolean ? \"true\" : \"false\", stdout); break;",
    "        case USK_FMT_NULL: fputs(\"null\", stdout); break;",
    "        default: fputs(\"<format-error>\", stdout); break;",
    "    }",
    "}",
    "static void usk_write(const UskFmtArg *values, size_t count) {",
    "    for (size_t index = 0; index < count; ++index) usk_print_arg(values[index]);",
    "}",
    "static void usk_writeln(const UskFmtArg *values, size_t count) {",
    "    usk_write(values, count);",
    "    fputc('\\n', stdout);",
    "}",
    "static void usk_writef(const char *format, const UskFmtArg *values, size_t count) {",
    "    if (!format) return;",
    "    size_t argument = 0;",
    "    for (size_t index = 0; format[index];) {",
    "        if (format[index] == '{' && format[index + 1] == '{') {",
    "            fputc('{', stdout); index += 2; continue;",
    "        }",
    "        if (format[index] == '}' && format[index + 1] == '}') {",
    "            fputc('}', stdout); index += 2; continue;",
    "        }",
    "        if (format[index] == '{' && format[index + 1] == '}') {",
    "            if (argument < count) usk_print_arg(values[argument++]);",
    "            else fputs(\"{}\", stdout);",
    "            index += 2; continue;",
    "        }",
    "        fputc((unsigned char)format[index++], stdout);",
    "    }",
    "}"
};

bool usk_c_emit_runtime_support(UskCEmitter *emitter) {
    if (!emitter) return false;
    size_t count = sizeof(runtime_lines) / sizeof(runtime_lines[0]);
    for (size_t index = 0; index < count; ++index) {
        if (!usk_c_emit_write(emitter, "%s\n", runtime_lines[index]))
            return false;
    }
    return usk_c_emit_write(emitter, "\n");
}
